#ifndef PROTOCOL_H
#define PROTOCOL_H
#include<stdlib.h>
#include<string.h>
typedef unsigned int uint;

#define SEND_APPLY "send application"
#define NOT_EXIST "no exist person"
#define IS_OFFLINE "person is offline"
#define ALREADY_FRIEND "you are already friends"
#define REGIST_0K "register ok"
#define REGIST_FAILED "regist failed: name existed"
#define LOGIN_0K "login success"
#define LOGIN_FAILED "login failed: name or pwd error"
#define ADD_SUCCESS "add friend success"
#define DEL_SUCCESS "delete success"
#define DIR_EXIST "dir is exist"
#define DEL_FAIL "delete fail"
#define DIR_SUCCESS "create success"
#define DIR_ERROR "FILE path is error"
#define DIR_NO_EXIST "dir is exist"
#define RENAME_SUCCESS  "rename success"
#define RENAME_FAIL  "rename fail"
#define REFUSE_ADD  "refuse add"
#define UPLOAD_FAIL "upload fail"
#define UPLOAD_SUCCESS "upload success"
#define SHARE_SUC "share success"
#define SHARE_FAIL "share ok"
#define MOVE_NOT_DIR "can not move to file"
#define MOVE_SUC "move success"
enum ENUM_MSG_TYPE{
    ENUM_MSG_TYPE_MIN=0,
    ENUM_MSG_TYPE_MAX=0X00ffffff,
    ENUM_MSG_TYPE_REGIST_REQUEST,
    ENUM_MSG_TYPE_REJIST_RESPONSE,
    ENUM_MSG_TYPE_LOGIN_REQUEST,
    ENUM_MSG_TYPE_LOGIN_RESPONSE,
    ENUM_MSG_TYPE_ALL_ONLINE_REQUEST,
    ENUM_MSG_TYPE_ALL_ONLINE_RESPONSE,
    ENUM_MSG_TYPE_SEARCH_REQUEST,
    ENUM_MSG_TYPE_SEARCH_RESPONSE,
    ENUM_MSG_TYPE_ADD_FRIEND_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPONSE,
    ENUM_MSG_TYPE_RESEND_FRIEND_REQUEST,
    ENUM_MSG_TYPE_RESEND_FRIEND_RESPONSE,
    ENUM_MSG_TYPE_RESEND_REFUSE_REQUEST,

    ENUM_MSG_TYPE_FLUSH_FRIEND_RESPONSE,
    ENUM_MSG_TYPE_FLUSH_FRIEND_REQUEST,

    ENUM_MSG_TYPE_DELETE_FRIEND_REQUEST,
    ENUM_MSG_TYPE_DELETE_FRIEND_RESPONSE,

    ENUM_MSG_TYPE_SEND_MESSAGE_REQUEST,
    ENUM_MSG_TYPE_SEND_MESSAGE_RESPONSE,

    ENUM_MSG_TYPE_CREATE_FILE_REQUEST,
    ENUM_MSG_TYPE_CREATE_FILE_RESPONSE,
    ENUM_MSG_TYPE_CREATE_DIR_REQUEST,
    ENUM_MSG_TYPE_CREATE_DIR_RESPONSE,
    ENUM_MSG_TYPE_CREATE_FLUSH_REQUEST,
    ENUM_MSG_TYPE_CREATE_FLUSH_RESPONSE,
    ENUM_MSG_TYPE_DEL_DIR_REQUEST,
    ENUM_MSG_TYPE_DEL_DIR_RESPONSE,
    ENUM_MSG_TYPE_RENAME_DIR_REQUEST,
    ENUM_MSG_TYPE_RENAME_DIR_RESPONSE,

    ENUM_MSG_TYPE_ENTER_DIR_REQUEST,
    ENUM_MSG_TYPE_ENTER_DIR_RESPONSE,
    ENUM_MSG_TYPE_UPLOAD_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_RESPONSE,
    ENUM_MSG_TYPE_DEL_FILE_REQUEST,
    ENUM_MSG_TYPE_DEL_FILE_RESPONSE,
    ENUM_MSG_TYPE_DOWNLOAD_REQUEST,
    ENUM_MSG_TYPE_DOWNLOAD_RESPONSE,
    ENUM_MSG_TYPE_SHARE_REQUEST,
    ENUM_MSG_TYPE_SHARE_RESPONSE,
    ENUM_MSG_TYPE_SHARE_RESEND_REQUEST,
    ENUM_MSG_TYPE_SHARE_RESEND_RESPONSE,
    ENUM_MSG_TYPE_MOVE_REQUEST,
    ENUM_MSG_TYPE_MOVE_RESPONSE,
};
struct FileInfo{
    char FileName[32];
    int fileType;
};
//消息协议
struct PDU{
    uint uiPDULen;
    uint uiMsgType;
    char caData[64];
    uint uiMsgLen;
    int caMsg[];
};

PDU *mkPDU(uint MsgLen);
#endif // PROTOCOL_H
